### ISSUE TITLE
error on macOS: The subversion command line tools are no longer provided by Xcode.

### ISSUE THREAD

**Issue by idbrii** [NibbleByte/UnityWiseSVN#1]
I have subversion and Unity installed via brew.

When I launch Unity, WiseSvn gives me this error:

```
IOException: Trying to get status for file Assets/blah caused error:
svn: error: The subversion command line tools are no longer provided by Xcode.


DevLocker.VersionControl.WiseSVN.WiseSVNIntegration.GetStatuses (System.String path, DevLocker.VersionControl.WiseSVN.SVNStatusDataOptions options, DevLocker.VersionControl.WiseSVN.Shell.IShellMonitor shellMonitor) (at Library/PackageCache/devlocker.versioncontrol.wisesvn@ed4144bdcf/Editor/WiseSVNIntegration.cs:300)
DevLocker.VersionControl.WiseSVN.WiseSVNIntegration.GetStatus (System.String path, DevLocker.VersionControl.WiseSVN.Shell.IShellMonitor shellMonitor) (at Library/PackageCache/devlocker.versioncontrol.wisesvn@ed4144bdcf/Editor/WiseSVNIntegration.cs:370)
DevLocker.VersionControl.WiseSVN.SVNStatusesDatabase.PostProcessAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets) (at Library/PackageCache/devlocker.versioncontrol.wisesvn@ed4144bdcf/Editor/SVNStatusesDatabase.cs:404)
DevLocker.VersionControl.WiseSVN.SVNStatusesDatabaseAssetPostprocessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Library/PackageCache/devlocker.versioncontrol.wisesvn@ed4144bdcf/Editor/SVNStatusesDatabase.cs:534)
...
```

At first I was very confused because I'd never relied on svn from Xcode nor had I configured WiseSvn (or anything else) to use Xcode's svn. I thought the error message was coming from WiseSvn and didn't clue in that it was coming from /usr/bin/svn until I searched the WiseSvn code to see where the error was defined.

# Solution

I figured out that Unity didn't have the correct path set.

[This post explains](https://apple.stackexchange.com/a/198282/268725) that you need to use launchctl to set your PATH for it to be respected by apps launched from the Dock. Since I have svn from brew, it's in `/usr/local/bin`:

```
sudo launchctl config user path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Once I'd done that, rebooted,  closed, and re-opened Unity, then it found my brew-installed svn.

Not sure if you want to handle this error somehow in code to help users figure this out, or close this issue and hopes that they find it.

Aside: This issue occurred despite having SnailSvn installed (but I'd never opened SnailSvn). Not sure if WiseSvn should have found the svn executable inside SnailSvn instead.

**Comment by NibbleByte** [comment]
Sorry for the long delay, didn't see the issue.
I'm a Windows user, so I'm not very familiar with macOS environment. 
Still, I've added proper message for command exceptions on startup and disable WiseSVN if that happens.
For OSX, if exception is IOException, I've added additional message that reads:

> If you installed SVN via Brew or similar, you may need to add "/usr/local/bin" (or wherever svn binaries can be found) to your PATH environment variable. Example:
> sudo launchctl config user path /usr/local/bin
> Alternatively, you may add relative SVN CLI path in your WiseSVN preferences ("Assets/SVN/SVN Preferences -> Project")

I believe this should be enough. 
I can't really test it, I don't have access to macOS at the moment. If you (or anyone) finds the time to test it and finds any issues, ping me.
