### ISSUE TITLE
Wise SVN Icons are being included in builds

### ISSUE THREAD

**Issue by TerminalJack** [NibbleByte/UnityWiseSVN#13]
Unity version 2022.3.18f1.  Wise SVN version 1.5.4.

When you build your game, several Wise SVN icons will be included in the build.  This adds about 1.3MB to the build size.

This screenshot is the Build Report for an empty project:

![image](https://github.com/NibbleByte/UnityWiseSVN/assets/56938265/a73085e1-820f-4552-9423-289ccd6c2ab7)

The easiest way to pull-up the Build Report is to use the Console window's hamburger menu, select 'Open Editor Log' and then search for 'Build Report'.  There may be more than one report in the log.  The bottom-most report will be for the most recent build.

![image](https://github.com/NibbleByte/UnityWiseSVN/assets/56938265/8f4a2aae-75d0-4711-965f-ffd437e7d480)

To prevent these files from being included, I moved the Resources folder (DevLocker/VersionControl/WiseSVN/Resources) under the Editor folder (DevLocker/VersionControl/WiseSVN/Editor).

![image](https://github.com/NibbleByte/UnityWiseSVN/assets/56938265/6e4c79ba-48eb-447c-8c99-59c51c83b11e)

This is the result:

![image](https://github.com/NibbleByte/UnityWiseSVN/assets/56938265/be2a7b91-c341-4703-8487-7321f3bc7ecb)

I didn't create a PR for this since I didn't know how you would want to handle it.  So far as I can tell, the 'Resources' folder will have to be under an 'Editor' folder and not the other way around, as it is now...

![image](https://github.com/NibbleByte/UnityWiseSVN/assets/56938265/33d87389-ee1a-4dcb-93be-a9bcb7c56c0b)

...and, if that's the solution then you would likely want to restructure the Resources folder to get rid of the, now unnecessary, 'Editor' folder.  However, this will require the path names in the code to be changed:

![image](https://github.com/NibbleByte/UnityWiseSVN/assets/56938265/1e46f2e6-25f4-4e5f-9cb1-06e1a3ff901f)

I have suspicions that the 'Resources' folder was placed outside of the 'Editor' folder intentionally.  (Perhaps it was a problem with older versions of Unity?)  Because of this, I didn't feel comfortable creating a PR.

**Comment by NibbleByte** [comment]
Well, my initial idea was to exclude the icons from the build, but I never actually checked if it did :D 
So yes, I'll have to restructure the folders the way you suggested.

**Comment by TerminalJack** [comment]
Sounds good.
