### ISSUE TITLE
Issues when building XR project

### ISSUE THREAD

**Issue by MatJab94** [NibbleByte/UnityWiseSVN#15]
When building, I get the following popup:
![image](https://github.com/user-attachments/assets/d2cebee9-58f6-4344-82ce-be968d28f616)
This 'Temp' directory gets created by Unity. Not sure what exactly is doing it, might be happening in general for XR projects, or because of something specific I use. Here's some info just in case:
- I use OpenXR, Unity's XR Interaction Toolkit and target Meta Quest 3 (so Android platform)
- I'm on Windows and use TortoiseSVN
- I'm currently on Unity 2022.3.34 and WiseSVN 1.5.6

Now, I can accept the popup/mark it to not ask again in this session, and the build seems to proceed correctly.
However, it's annoying to accept this popup every time, even if it can be disabled for the session - it's not uncommon for me to switch between different projects throughout a day, and it's easy to forget that I restarted Unity, so the popup will block the building process until I notice etc. Very annoying.

I tried adding this directory to 'Excluded Paths' in WiseSVN preferences. First I tried `Assets\XR\Temp` but that didn't work - still got the popup. Then I changed it to just `XR\Temp` and this time it seemed to have worked - build proceeded without a popup.
But at the end I got another popup about some SVN errors I should take a look at in the console. Sadly, I don't have the exact logs anymore, and for some reason I can't reproduce it - when I reverted all changes and tried again, with that path added to 'Excluded', it no longer seems to work and I keep getting the initial popup instead. But from what I recall, the issue was with the two files that it tries to move to this Temp directory, and then move back to original folder or something like that - and that second move didn't work because the directory was not under version control.

I did figure out a workaround for this issue - I just commited this empty directory (`Assets\XR\Temp`) to the repository and I no longer get the annoying popup nor any errors when building. But I wanted to mention the issues anyway, to potentially find a more proper fix, or for anyone who might have the same issue and need a temporary workaround.

Not sure what a proper fix should be though, maybe some of these would make sense?
- option in WiseSVN preferences to auto-accept the popup about unversioned directories (there's already a similar option: 'Ask On Moving Folders')
- ignoring changes that happen 'during a build' (I'm guessing these specific files are moved on PreProcessBuild and PostProcessBuild)

**Comment by NibbleByte** [comment]
Apologies for the inconvenience, I missed this corner-case.
I'm disabling file operations monitoring while building the player or in batch mode, i.e.  `Application.isBatchMode || BuildPipeline.isBuildingPlayer`.

You can download the latest version from the upm branch or wait for it to be published.
