### ISSUE TITLE
svn: E200007: Cannot move path '...' into itself

### ISSUE THREAD

**Issue by ScPhilip** [NibbleByte/UnityWiseSVN#16]
It is currently not possible (on Windows) to rename a folder when only changing case. I.e., you can't rename FOLDER to Folder. 

SVN Operations:
C:/Program Files/TortoiseSVN/bin/svn.exe move "FOLDER@" "Folder"
svn: E200007: Cannot move path 'FOLDER' into itself

UnityEngine.Debug:LogError (object)
DevLocker.VersionControl.WiseSVN.WiseSVNIntegration/ResultConsoleReporter:Dispose () (at Assets/Imports/DevLocker/VersionControl/WiseSVN/Editor/WiseSVNIntegration.cs:252)
DevLocker.VersionControl.WiseSVN.WiseSVNIntegration:OnWillMoveAsset (string,string) (at Assets/Imports/DevLocker/VersionControl/WiseSVN/Editor/WiseSVNIntegration.cs:2041)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by NibbleByte** [comment]
This is an issue with svn itself, probably Windows only. Even the Windows file browser doesn't allow you to do that (seems it do, but it doesn't). I can try and detect such renames and make it into two-steps.

As a workaround, you can just rename the folder to something else then rename it again to the desired name.

**Comment by ScPhilip** [comment]
TortoiseSVN on Windows does this properly (Rightclick on Folder > TortoiseSVN > Rename), but it's possible that they have a workaround as well. It's not a critical issue obviously, just thought I'd let you know. :-)

**Comment by NibbleByte** [comment]
Yeah, I meant the svn.exe command. I've seen this happen before and it is annoying, I think it's about time I fix it. 😄

**Comment by ScPhilip** [comment]
Wow, this must have been the fastest report-to-fix I have seen in my 20+ years as a software developer. Hats off to you, my man.
