### ISSUE TITLE
Error thrown on excluded file.

### ISSUE THREAD

**Issue by lmeunierATF** [NibbleByte/UnityWiseSVN#4]
We noticed in the project I work on that there is a bug with some excluded files. In our automation, the plugin throw an error because it tries to delete an excluded file.
Problem occurs with the use of adressables (the file causing the error was a link.xml generated by adressables in unity)

![Capture d’écran 2023-03-16 091833](https://user-images.githubusercontent.com/80534472/225557138-e1b34d1b-66cf-41e0-85ff-d1fcf4935a18.png)

**Comment by NibbleByte** [comment]
Hello,

Yes, this seems like a very rare corner-case I missed. I'll patch it up. In the meantime, you can just tweak the code yourself so you don't get this error.
Change the lines after ".meta" deletion (not sure which row, your file looks outdated):

```
result = ShellUtils.ExecuteCommand(SVN_Command, $"delete --force \"{SVNFormatPath(path + ".meta")}\"", COMMAND_TIMEOUT, reporter);
if (result.HasErrors)
    return AssetDeleteResult.FailedDelete;
```
... to...
```
result = ShellUtils.ExecuteCommand(SVN_Command, $"delete --force \"{SVNFormatPath(path + ".meta")}\"", COMMAND_TIMEOUT, reporter);
if (result.HasErrors) {
    reporter.ClearLogsAndErrorFlag();
    return AssetDeleteResult.DidNotDelete;
}
```

If your project has custom build script or any other automation, I'd suggest adding `WiseSVNIntegration.RequestTemporaryDisable()` at the start of the process and `WiseSVNIntegration.ClearTemporaryDisable()` at the end of it, preferably in try-finally block. This will disable the WiseSVN plugin from monitoring the file operations so SVN won't get in the way.

Cheers :)
