### ISSUE TITLE
SnailSVN non free version support

### ISSUE THREAD

**Issue by larssteenhoff** [NibbleByte/UnityWiseSVN#5]
Hi I'm using the payed version of SnailSVN, can you add support for that?

**Comment by NibbleByte** [comment]
I don't have the payed version and I'm having trouble accessing a Mac at the moment.
For the context menus, I just run the SnailSVN bash script: `/Applications/SnailSVNLite.app/Contents/Resources/snailsvn.sh`
Can you tell me where this script is located for the payed version? (probably just need to remove the "Lite" part)

**Comment by larssteenhoff** [comment]
> I don't have the payed version and I'm having trouble accessing a Mac at the moment.
> For the context menus, I just run the SnailSVN bash script: `/Applications/SnailSVNLite.app/Contents/Resources/snailsvn.sh`
> Can you tell me where this script is located for the payed version? (probably just need to remove the "Lite" part)

Yes just remove the "Lite" and it will work, 
![Screenshot 2023-04-06 at 11 17 31](https://user-images.githubusercontent.com/9589240/230332795-ffc7aa81-7b07-41ce-9fc8-2795866a9514.png)

Can you make it so that it will work whether light or normal version are installed?

**Comment by larssteenhoff** [comment]
![Screenshot 2023-04-06 at 11 24 35](https://user-images.githubusercontent.com/9589240/230334346-edf50eb7-92ac-4579-a4f5-49697e8b5f5e.png)

Seems adding it here makes the most sense

**Comment by NibbleByte** [comment]
Check my commit, it should work for both versions now. I just check which of the files exist and use that one - no additional preference menu. You can just download and replace the whole SnailSVNContextMenus.cs file.

**Comment by larssteenhoff** [comment]
Super! Thanks

**Comment by larssteenhoff** [comment]
![Screenshot 2023-04-06 at 11 50 40](https://user-images.githubusercontent.com/9589240/230342098-5b6dcd04-60ad-4b82-9f76-79d01d36e6bd.png)

not sure if it matters but there is still some references to the free version when opening the application url

**Comment by NibbleByte** [comment]
Damn it. Check if `Right-click / SVN / Check Changes` works. If it does, it means the payed version uses the same protocol. If not, I'll make a "snailsvn://" version, probably that's the one.

**Comment by larssteenhoff** [comment]
I changed the code to remove free and then it works, snailsvn:// is the one indeed

Without changing the code it did not work.

**Comment by NibbleByte** [comment]
Made the code work with both, again. Thanks :)
