### ISSUE TITLE
Linux/Command line support

### ISSUE THREAD

**Issue by karakune** [NibbleByte/UnityWiseSVN#6]
Hi there,

The plugin has been very useful at my workplace, so thank you for that. However, one of the machines runs on linux and cannot use the plugin, because neither Tortoise or Snail are available on that.

Would it be possible to add CLI SVN as an option for the context menu client? This way, the plugin would truly be platform agnostic.

Thank you for your work

**Comment by NibbleByte** [comment]
That's not a bad idea. But then the context menus will not show any window, just execute operation silently in the background. In that case how would commit from the context menu look like? I don't want to make custom editor windows for those menus, as this would require more work and support. :(

Note that the plugin should work on Linux for file operations (move/rename/delete assets in Unity). Only the context menus won't work.

**Comment by NibbleByte** [comment]
This is what I came up with. Added new context menu option - "CLI". With it all menus open this editor window. The top is the input that is automatically filled in by the context menu, but user can modify it. The "Run" button starts the command and the output is printed out in the bottom field.
![image](https://github.com/NibbleByte/UnityWiseSVN/assets/2332996/d9ff0d5f-23c2-416a-8708-3e32795dca35)
