### ISSUE TITLE
RabbitVCS SVN support

### ISSUE THREAD

**Issue by EmiyaSyahriel** [NibbleByte/UnityWiseSVN#7]
Please support RabbitVCS SVN as a context menu client. RabbitVCS is GUI-based SVN (and also Git) client for Linux.

My team is using this plugin on Windows' TortoiseSVN and it works perfectly with my team's current workflow. But, now I have to use Linux (Ubuntu specifically) for testing and building since my team's current project also targets Linux. For now I'll resort to RabbitVCS' context menu in Nautilus file manager instead since it is the second fastest thing.

It might be a complement to issue #6, since #6 also have something to do with Linux, but it was specific for CLI. And although you can also launch the RabbitVCS' GUI via command line, adding it directly as an option may saves a lot of time.

**Comment by NibbleByte** [comment]
Merged the pull request.
Thanks again for your contribution, I'll add your name in the change logs :)
